# -*- coding: utf-8 -*-
"""mreales_Quiz1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PdUNMZWpv72c_e6VAMs4whvT6-XerDXL

#Quiz 1 Desarrollo
##Miguel Angel Reales
"""

def FizzBuzz(x):
  if x % 3==0 and not (x % 5 == 0 ):
    return "Fizz!"
  elif x % 5==0 and not (x % 3 == 0 ):
    return "Buzz!"
  elif x % 3 == 0 and x % 5 == 0:
    return "FizzBuzz!"
  else:
    return "..."

def FizzBuzzList(n):
  respuesta=[]
  for i in range(n):
    respuesta.append(FizzBuzz(i+1))
  return respuesta

import numpy as np

def standarize(X):
  X_standarized = (X-X.mean())/X.std()
  return X_standarized

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float)
  return D